### ISSUE TITLE
是否可以考虑默认只展示当前文件以及子文件的时间轴

### ISSUE THREAD

**Issue by pokerLL** [BryceAndJuly/Document-Timeline#1]
这个挂件整体还是蛮让我惊喜的，但是我的笔记总共有1000多篇，所以操作的时候非常卡顿，基本处于不可用的状态，所以作者是否考虑做一个配置让我们选择是加载全局还是只加载当前文件以及子文件，这样子卡顿的问题能解决很多

具体的设计方面可以参考listchilddoc

**Comment by BryceAndJuly** [comment]
顶栏的时间段聚焦其实就有缓解卡顿的作用。比如聚焦到最近一个月后，随着显示的节点的减少，会顺畅很多。
