### ISSUE TITLE
提议：记住当前缩放比例和位置

### ISSUE THREAD

**Issue by winter60** [BryceAndJuly/Document-Timeline#2]
记住当前缩放比例和位置，便于下次打开能直接看到之前大概位置，不用每次都调整缩放比例并拖动到指定位置。

**Comment by BryceAndJuly** [comment]
或许可以弄成：

* 时间轴拖拽或者缩放后，自动将当前视窗的起止时间写到顶栏的时间段里，然后时间段的值保存到local.json里（目前是存到LocalStorage)；这样刷新后就有上次的视窗起止时间。
* 这样的话，刷新后，点一下时间段【聚焦】就能聚焦到上次浏览的位置了。

**Comment by BryceAndJuly** [comment]
我刚刚试了一下，监听时间轴的变动能拿到变动后视窗的起止时间，但是在初始化的时候也会触发并覆盖掉，暂时没想到啥好办法。要不你在顶栏手动设置一下常用的时间段吧，我把那个顶栏起止时间改成保存到local.json了，确保重新打开软件后顶栏时间段的值不被清空。——之前的是临时存到localStorage。
如果你刚好想到其他办法，可以一起分享一下。可行的话，下版更新到集市上。

**Comment by BryceAndJuly** [comment]
[index.zip](https://github.com/BryceAndJuly/Document-Timeline/files/10833099/index.zip)

**Comment by winter60** [comment]
除了存在文件里面外，还可以存在挂件块的属性里面。块里面可以保证不同地方使用的时间范围为独立的，可以参考集市的一些挂件。
