### ISSUE TITLE
提议：聚焦能快速点选近一个月等时间段

### ISSUE THREAD

**Issue by whzecomjm** [BryceAndJuly/Document-Timeline#3]
RT. 因为笔记很多，全部显示较慢，是否能提供近一个月的聚焦快速点选按钮（以及保存设置）？

**Comment by BryceAndJuly** [comment]
【聚焦时间段】已经设置的起止时间点目前是保存在LocalStorage里的，我本地设置了指定端口启动，所以重启软件也不会掉数据。

这样吧，我改成把那个设置的起止时间点保存到块属性里，这样每次打开都是上次设置好的起止时间，就不用每次都设置起止时间了。

**Comment by whzecomjm** [comment]
👍

**Comment by BryceAndJuly** [comment]
- 挂件仓库已经更新了，也发布了Release，集市那边过段时间应该会自动更新的。
- 或者可以直接下载仓库的压缩包，解压后给挂件文件夹改个名字，然后放进挂件目录也可以用。
- 我在V2.7.2上刚刚试了下是没问题的，有问题的话，直接在这个issue下回复我就行了。

[https://github.com/BryceAndJuly/Document-Timeline/releases/tag/1.1](https://github.com/BryceAndJuly/Document-Timeline/releases/tag/1.1)
