### ISSUE TITLE
Bugs in latest version of SiYuan-2.8.8

### ISSUE THREAD

**Issue by himawork** [BryceAndJuly/Document-Timeline#4]
Too many records in lastest version cannot be displayed.

**Comment by BryceAndJuly** [comment]
感谢反馈，我自己的笔记版本不经常更新，所以无法第一时间获知挂件在新版笔记中出现的问题。
刚刚发布了一个版本解决了你提到的问题，如果你在使用过程中还发现其他问题，可以继续在Github上给我留言。
[https://github.com/BryceAndJuly/Document-Timeline/releases/tag/1.2](https://github.com/BryceAndJuly/Document-Timeline/releases/tag/1.2)
